version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jsonpickle
    versions:
    - 1.5.0
    - 1.5.1
  - dependency-name: internetarchive
    versions:
    - 1.9.6
    - 1.9.9
  - dependency-name: pytest
    versions:
    - 6.2.1
    - 6.2.2
  - dependency-name: pymarc
    versions:
    - 4.0.0
